### ISSUE TITLE
Updating constraint values

### ISSUE THREAD

**Issue by nyxaria** [kktse/slvstopy#67]
Hello,

I am right now trying to analyse a linkage through slvstopy, with the aim of changing the value of a distance or angle constraint, solving and then analysing the points of the linkage. I have thus far managed to load the slvs file, and extract the constraints and line, and point entities that I need to do this. However when I try to update the value 'valA' of the angle or distance constraint for a line, when I solve the points do not get updated but remain constant. This leads me to assume that the way I am changing them is not propagating to the root implementation of solvespace. My code is below, do you mind helping me in how I should approach this please?

```
slvs_to_py = Slvstopy(file_path="rotx_2S1Pdiagonal_todo.slvs")
system, entities, cr = slvs_to_py.generate_system()

print("distances:", [(x['h']['v'], x['valA'], x["ptA"]["v"], x["ptB"]["v"]) for x in slvs_to_py.constraint_definition if x['type'] == '30' and x['reference'] == '0'])
print("angles:", [(x['h']['v'], x['valA']) for x in slvs_to_py.constraint_definition if (x['type'] == '120' and x['reference'] == '0')])

points = []
points.append(system.params(entities["00040001"].params))  # origin
points.append(system.params(entities["00040002"].params))  # tip of motor rod
points.append(system.params(entities["000f0002"].params))  # slider link

# pprint(points)
# probe_point = system.params(entities["00120002"].params)
# print(probe_point)

# # how to change contraints TODO
probe_dist_constraint = slvs_to_py.constraint_definition.index([x for x in slvs_to_py.constraint_definition if x['h']['v'] == '00000027'][0])
t01_constraint = slvs_to_py.constraint_definition.index([x for x in slvs_to_py.constraint_definition if x['h']['v'] == '0000002d'][0])

# I tried constructing a new angle constraint to replace the old one but this fails for some reason
# the current angle is ~172 as seen from the point out above
# system.angle(entities.get(t01['entityA']['v']), entities.get(t01['entityB']['v']), 170)

# these do not actually update the linkage points when I solve below
slvs_to_py.constraint_definition[t01_constraint]['valA'] = 172
slvs_to_py.constraint_definition[probe_dist_constraint]['valA'] = 20

# print([x for x in entities if x.is_distance()])

# this doesn't work, I'm not sure how to use this for constraints rather than entities
# system.set_params(
#     entities[t01_constraint],
#     (170),
# )

print('test points before')
print(system.params(entities["00040002"].params))
probe_point = system.params(entities["00120002"].params)
print(probe_point)
if system.solve() == ResultFlag.OKAY:
    print('success')
    print('test points after')
    print(system.params(entities["00040002"].params))
    probe_point = system.params(entities["00120002"].params)
    print(probe_point)
else:
    # Error!
    # Get the list of all constraints
    failures = system.failures()
    print("FAIL", failures)
```
[rotx_2S1Pdiagonal_todo.slvs.zip](https://github.com/kktse/slvstopy/files/11961247/rotx_2S1Pdiagonal_todo.slvs.zip)

**Comment by nyxaria** [comment]
I did some digging through https://github.com/KmolYuan/solvespace/blob/python/cython/python_solvespace/slvs.pyx and it seems like what I need is the `cons_list`, but I can't seem to access it from my code. Do you know how we can access it or if it is even exposed?

The only other way I can think of is by directly editing the `slvs` file and reloading it in python, but this seems _super_ hacky

**Comment by kktse** [comment]
It has been a bit of time since I have worked on this library, here is what I recall.

The `python-solvepsace` library has the quirk of one system, one solution. Consequently, each displacement of your driven link will need to be a new system. I do not recall exactly what happens if you try to update a constraint or solve the system again, but I distinctly remember avoiding updating constraints.

With the above workflow in mind, just leave the driven link unconstrained in the `*.slvs` file and then constrain it in code, then solving for the system. The position of the linkage at the time of saving will be the initial state in the `*.slvs` file.

It does require a bit of application specific boilerplate but it does automate nicely once its done.

**Comment by nyxaria** [comment]
Thank you so much @kktse that sounds like exactly what I am looking for. Do you mind answering how you constrain the angle between two 3d lines in your code? I can't seem to get it working

**Comment by kktse** [comment]
I took a closer look at this for you.

**Drawing changes**: I simplified the drawing of the slider-crank mechanism. Compatibility between SolveSpace and `python-solvespace` requires a great deal of consideration, so there is a degree that you have to draw for compatibility and analysis. These changes and strategies include:

* Drawing in a single "Sketch in 3D" group and deleting the default workplane sketch. This gets rid of some implicit constraints that result in differences between the app and the library.
* Using "where dragged" constraints for fixed locations to cut down on complex constraints. You can fix points by dimensioning them in 3D, overconstraining it with the dragged constraint and then deleting the dimensions.
* Ensuring that SolveSpace indicates that there is only 1 DoF

**Constraining the crank**: there is indeed a way to add an angle in 3D in `python-solvespace` using the `add_constraint` method. Here is the behinds the scenes of how I am doing this as part of this library.

https://github.com/kktse/slvstopy/blob/50f14ca36b0ee0d8240939c6689cb18b48a81ccb/src/slvstopy/repositories.py#L312-L326

I've included a gist with some sample code and the modified drawing to demonstrate how I got things to work. https://gist.github.com/kktse/5211f68df282c6c6281f2e6b95ebbad8

**Comment by nyxaria** [comment]
@kktse Thank you so much for your help in this, and for the gist! Your help is invaluable!
